name: Compile sketches to verify dependencies
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify sketches
        uses: abstract-333/compile-sketches@v1.1.0
        with:
          enable-cache: true
          fqbn: "arduino:zephyr:unoq"
          sketch-paths: "./examples"